# Generated by Django 3.0.2 on 2020-02-26 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_action_bathroom_category_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='Actions',
            new_name='name_of_actions',
        ),
        migrations.RenameField(
            model_name='bathroom',
            old_name='bathrooms',
            new_name='number_of_bathrooms',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='categories',
            new_name='name_of_categories',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='cities',
            new_name='name_of_cities',
        ),
    ]
