# Generated by Django 3.0.2 on 2020-03-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20200226_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name_of_cities',
            field=models.CharField(max_length=100),
        ),
    ]
