# Generated by Django 3.0.2 on 2020-03-07 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20200301_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='action',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Action'),
            preserve_default=False,
        ),
    ]
